#------Ejemplo: simulación sencilla--------# 

#-------------------oooooOOOOO00000OOOOOooooo---------------------#


#=====================================================
# VERBOSE and VISUALISATION
#=====================================================

/control/execute mac/verbose.mac

# to use the visualisation :
#   - uncomment the following line
#   - use Gate --qt
#   - in the interface, type /control/execute mac/main.mac
#/control/execute mac/visu.mac



#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase                 data/GateMaterials.db

# WORLD
/gate/world/setMaterial                      Air
/gate/world/geometry/setXLength              100 cm
/gate/world/geometry/setYLength              100 cm
/gate/world/geometry/setZLength              100 cm

# DAUGHTER
/gate/world/daughters/name                     vol_name
/gate/world/daughters/insert                   sphere
/gate/vol_name/setMaterial                     Lung
/gate/vol_name/geometry/setRmin                0.0 cm
/gate/vol_name/geometry/setRmax                15.0 cm
/gate/vol_name/placement/setTranslation        0 0 0 cm
/gate/vol_name/vis/forceSolid
/gate/vol_name/vis/setColor                    white

# PHANTOM
/gate/world/daughters/name                   my_phantom
/gate/world/daughters/insert                 cylinder
/gate/my_phantom/setMaterial                 Water
/gate/my_phantom/geometry/setRmax            10. mm
/gate/my_phantom/geometry/setHeight          30. mm
/gate/my_phantom/placement/setTranslation    0 0 0 cm
/gate/my_phantom/vis/forceSolid
/gate/my_phantom/vis/setColor                grey



#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList QGSP_BERT_HP_EMY

/gate/physics/addProcess HadronElastic Default
/gate/physics/processes/HadronElastic/setModel G4LElastic Default

/gate/physics/addProcess NeutronCapture
/gate/physics/processes/NeutronCapture/setModel G4LCapture

/gate/physics/addProcess NeutronInelastic
/gate/physics/processes/NeutronInelastic/setModel PreCompound

/gate/physics/addProcess Fission
/gate/physics/processes/Fission/setModel G4LFission



#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize



#=====================================================
# BEAMS
#=====================================================
/gate/source/addSource                 Neutron  gps 
/gate/source/Neutron/gps/particle      neutron
/gate/source/Neutron/gps/energytype    Mono 
/gate/source/Neutron/gps/monoenergy    10. keV

/gate/source/Neutron/gps/pos/type        Plane
/gate/source/Neutron/gps/pos/rot1        0 1 0
/gate/source/Neutron/gps/pos/rot2        1 0 0
/gate/source/Neutron/gps/pos/shape       Circle
/gate/source/Neutron/gps/pos/radius      30 cm



#=====================================================
# OUTPUT - DETECTOR
#=====================================================

/gate/actor/addActor                       DoseActor  doseIn3D
/gate/actor/doseIn3D/save                  output/Ejemplo.txt
/gate/actor/doseIn3D/attachTo              my_phantom
/gate/actor/doseIn3D/stepHitType           random
/gate/actor/doseIn3D/setPosition           0 0 0 cm
/gate/actor/doseIn3D/setVoxelSize          1 1 1 cm
/gate/actor/doseIn3D/enableEdep            true
/gate/actor/doseIn3D/enableUncertaintyEdep true
/gate/actor/doseIn3D/enableDose            true
/gate/actor/doseIn3D/enableUncertaintyDose true
/gate/actor/doseIn3D/enableDoseToWater     true
/gate/actor/doseIn3D/saveEveryNSeconds     3000



#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 3700

/gate/application/start